### ISSUE TITLE
Recreate it to a camt.053 to OFX converter

### ISSUE THREAD

**Issue by ghost** [bluesnotred/mt940_to_ofx#1]
As a camt.053 to OFX converter, much more people can benefit from it.

http://www.ofx.net/

"Choose OFX format, before QIF or CSV format, if your online banking offers it." (Source: Xero, http://help.xero.com/help/BankImportOFX.htm)

"Voor SEPA-betaalproducten is een nieuw rapportageformaat geïntroduceerd: CAMT. Het CAMT-rapportageformaat bevat gedetailleerde informatie over SEPA-transacties. De Nederlandse Betaalvereniging heeft hiervoor 'Implementation Guidelines' opgesteld." (Source: ABN AMRO, https://www.abnamro.nl/nl/zakelijk/betalen/sepa/downloads.html)

**Comment by bluesnotred** [comment]
Unfortunately, Dutch banks do not offer camt.053 by default. With ING Bank, for example, you need their "InsideBusiness Payments" subscription. Some banks do not offer it at all. That's why we stick to the MT940 format for now. 

In the past we did successfully test a camt.053 to OFX script, so when I've got some spare time, I will include it in this repository.

**Comment by bluesnotred** [comment]
A few things have changed since 2015:
- Xero now offers bank feeds for ING Bank (based on screen scraping with Yodlee, so **not reliable**)
- ING offers a camt.053 export for **all** business customers (not just for InsideBusiness Payments )

Because the Yodlee bank feeds are so unreliable, we eventually created a camt.053 to ofx script. It's much more reliable than the "automatic bank feeds" via Yodlee. Also, you don't have to share your confidential username and password with Yodlee.

You can find the script over here:
https://github.com/bluesnotred/camt2ofx
